/** BFF 自有错误码（与 apps/bff/src/errors.ts 一一对应）。 */
export type WebuiErrorCode =
  | 'WEBUI_SESSION_REQUIRED'
  | 'WEBUI_SESSION_EXPIRED'
  | 'WEBUI_CSRF_REJECTED'
  | 'WEBUI_ORIGIN_REJECTED'
  | 'WEBUI_HOST_REJECTED'
  | 'WEBUI_METHOD_NOT_ALLOWED'
  | 'WEBUI_ROUTE_NOT_ALLOWED'
  | 'WEBUI_UNSUPPORTED_CONTENT_TYPE'
  | 'WEBUI_INVALID_REQUEST'
  | 'WEBUI_PAYLOAD_TOO_LARGE'
  | 'WEBUI_RATE_LIMITED'
  | 'WEBUI_CAPACITY_EXCEEDED'
  | 'WEBUI_UPSTREAM_UNREACHABLE'
  | 'WEBUI_UPSTREAM_TIMEOUT'
  | 'WEBUI_UPSTREAM_UNEXPECTED_CONTENT'
  | 'WEBUI_UPSTREAM_REDIRECT_BLOCKED'
  | 'WEBUI_RESPONSE_TOO_LARGE'
  | 'WEBUI_NOT_FOUND'
  | 'WEBUI_NOT_READY'
  | 'WEBUI_INTERNAL'
  | 'WEBUI_NETWORK_ERROR';

/** 传输类错误：说明 WebUI 与 Parrot 之间的链路有问题，而不是业务被拒绝。 */
export const TRANSPORT_ERROR_CODES: readonly string[] = [
  'WEBUI_UPSTREAM_UNREACHABLE',
  'WEBUI_UPSTREAM_TIMEOUT',
  'WEBUI_UPSTREAM_UNEXPECTED_CONTENT',
  'WEBUI_UPSTREAM_REDIRECT_BLOCKED',
  'WEBUI_RESPONSE_TOO_LARGE',
  'WEBUI_NETWORK_ERROR',
  'WEBUI_NOT_READY',
];

/** 上游 Parrot 的业务错误码（用于分支处理，不是全部枚举）。 */
export const UPSTREAM_CODE = {
  REVISION_CONFLICT: 'REVISION_CONFLICT',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CAPABILITY_DENIED: 'CAPABILITY_DENIED',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_NOT_READY: 'SERVICE_NOT_READY',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  OPERATION_NOT_FOUND: 'OPERATION_NOT_FOUND',
  OPERATION_ALREADY_RUNNING: 'OPERATION_ALREADY_RUNNING',
  IDENTITY_CONFLICT: 'IDENTITY_CONFLICT',
  CONFIRMATION_REQUIRED: 'CONFIRMATION_REQUIRED',
  INVALID_OPERATION_STATE: 'INVALID_OPERATION_STATE',
  STATE_CONFLICT: 'STATE_CONFLICT',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  SESSION_REQUIRED: 'SESSION_REQUIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  ORIGIN_DENIED: 'ORIGIN_DENIED',
} as const;

/**
 * 上游可能把"保存成功但运行时重载未确认"放在 503 + fields 中，
 * 需要按字段 code 判断，不能按 HTTP 503 一概重试。
 */
export const SAVED_RELOAD_UNCONFIRMED = 'SAVED_RELOAD_UNCONFIRMED';
